### PR TITLE
testing migration

### PR DESCRIPTION
**Pull request by ejether**

### CODE REVIEW

**Comment by sudermanjr** [comment]
I haven't kept up with the recent errors during migration, but it looks like this test is intended to make sure that the migration can actually run, correct?  If so, looks awesome.

**Comment by ejether** [comment]
It should test that a migration from a repo that is up-to-date with n-1 version standard will succeed. There are lots of ways this could fail in the real world, but this would catch errors like we had today where there was a syntax issue.

**Comment by endzyme** [comment]
nice - is this a final PR? I see that there is a `|| true` in the test and some note that mentions it's a known issue.

Outside of that stuff I think this is great. From a maintenance perspective I'm interested what else needs to be updated to make these tests work. Is there some other state somewhere? 

If we're trying to address the other day's issue, a unittest also would have found the problem by invoking the module.

**Review by dosullivan — APPROVED** [review]
Looks good to me!

**Comment by ejether** [comment]
@endzyme this a final PR. The `|| true` is required because otherwise when that `pip install pentagon==` command fails, it ends the build. The expectation is that the command will fail, but we need the STDERR to parse the available versions. 

I don't think unittesting is the right way to go for the individual migrations.

**Comment by endzyme** [comment]
Ohhhhh - that's not entirely clear from the comment inline - thanks for the context

**Pull request merged**
