### PR TITLE
Add default getting started docs

### PR DESCRIPTION
**Pull request by philipcristiano**
Add docs for generated repositories that list how to get started.

Not yet complete, still missing parts for Ansible.

### CODE REVIEW

**Comment by philipcristiano** [comment]
May change with #27 and #31 depending on their resolution.

**Comment by ejether** [comment]
I like the document and the information it provies. Is the idea to have this doc in every infrastructure repository created? Why not have it in the `docs/` directory?  Now that the repo is open source, I don't see the need to have the docs duplicated in every client repository. What are your thoughts?

**Comment by philipcristiano** [comment]
Yes, the idea is to have it in every repository. If the docs are hosted in a global location then repositories that don't keep up will get stale. Releases could solve that if we keep docs for each version available. Having per-repo docs also allows for customization for clients that don't continue with RO. 

I used `README.md` partially because it exists and wasn't helpful. I believe the `README.md` should be able to point to give general guidelines and what's needed to make the repo work, without needing to looks around the repo to find it.

**Comment by ejether** [comment]
I'd rather see us spend time working toward releases than updating docs in
two locations. I agree with your thoughts on what the readme should do, but
I think we have enough locations where documents exist.

The way I think about it is, when you create project with rails or django,
you still go to their repo or docs site for docs. There is work to do with
making the docs better, better versioned and more accessible.

I like the content of this readme a lot and I'd prefer it in `/docs`
instead of `/lib/docs`

**Comment by philipcristiano** [comment]
In my mind the `docs` folder are for docs about Pentagon while the docs in `lib/pentagon` are for docs about how to use the repository. We also have `README.md`s scattered through the generated repository, do you think those get moved into `docs` as well? 

I'd like to see these docs merged in a useful way for new customers until we get to the point where releases and common docs are more useful. We don't have much dev work at the moment to make those things happen quickly. Until we have these kinds of docs I wind up copying these getting started into the repo so they match what is happening for our customers and not what the current dev looks like.

**Review by ghost — APPROVED** [review]

**Review by sairez — APPROVED** [review]

**Comment by sairez** [comment]
I would lean toward having it in every repo generated (`lib/docs`).  Especially since it would capture the usage notes at the point in time at which you generate your project, which would ostensibly keep up with releases.

**Comment by ejether** [comment]
I'm lodging my continued objection to this course of action but accepting that I am in the minority.

@philipcristiano  I would like to see all the various readme condensed into a single location.  I would also like to see common docs and actual releases.  I will continue to work towards that as I can. In the meantime, if this PR saves you time. I'll merge it.

**Pull request merged**
