### PR TITLE
WIP: End-user Kubernetes docs, runbooks and templates

### PR DESCRIPTION
**Pull request by sairez**
Current Behavior
----------
* End users who have no familiarity with Kubernetes do not have any documentation regarding application lifecycle, resource management, proper usage, etc.

Why Change?
---------
* Provide some basic, generic, useful information regarding creation, usage and management of Kubernetes resources in an application lifecycle.

Implementation Details
------------
* Provide easy, grokable information about different Kubernetes resource types
* Provide runbooks for common ops procedures
* Provide example application templates for easy onboarding
* Provide FAQ or HOWTO articles 

Side Effects
----------
N/A

Documentation
----------
* Self documenting

Metrics
----------
N/A

Run Plan
----------
N/A

### CODE REVIEW

**Comment by kenm47** [comment]
files titled x- need to be fleshed out and are as-yet incomplete

**Comment by kenm47** [comment]
The remaining documentation I have from @philipcristiano and I'm not sure where to put it is:

There is a deployments file, but that feels more k8s specific and less specific to pentagon. There is also an application-onboarding file which may be suitable for the application configuration section.

```
# Deployments

Deployments manage Replica Sets of pods. Deleting a Deployment will not remove the Replica Set. 

Follow the `rok8s-scripts` [examples](https://github.com/reactiveops/rok8s-scripts/tree/master/examples/production-ready/deploy) for deployments. Be sure to set `revisionHistoryLimit` at minimum to prevent old Replica Sets from accumulating in Kubernetes.




# Application Configuration

Config maps should be used for application configuration. 

Volume mounting a configmap is preferable to environment variables. 

  - Volume mounted configmaps can update in a pod when a configmap changes (where as environment variables will not).
  - Environment variable configuration in deployments are burdensome. It’s possible to use tools to help with this but without additional tools it looks like 
            - name: ENVIRONMENT_VARIABLE_NAME
              valueFrom:
                configMapKeyRef:
                  name: CONFIGMAP_NAME
                  key: CONFIGMAP_KEY


## Updating Configuration

Most apps will not re-read configuration after they have started. **Pushing out a configmap change will not trigger a restart of pods** but there is a [Github issue](https://github.com/kubernetes/kubernetes/issues/22368). 

This is a reason to tie the config changes with the deployment. The code push will trigger CI to create a new deployment with a new image tag. The config changes will be pushed and all current pods replaced with new pods that include the config change. 


## Secrets

Secrets in Kubernetes are [not encrypted](https://github.com/kubernetes/kubernetes/issues/12742) in the standard deployment. Vault may eventually be used in our standard deployment to provide secure storage of secrets. It also has the benefit that it can be used by non-Kubernetes resources and potentially allow a simplified migration procedure if a client is already using Vault.

[rok8s-scripts includes support for the CI system to create Kubernetes Secrets](https://github.com/reactiveops/rok8s-scripts#k8s-secrets-from-s3). **Plain text secrets should never be included in the source code repository**. 

There are (at least) 2 ways we have included secrets with rok8s-scripts automation:

Store the data in S3, build the Kubernetes Secrets resource on the CI server, then upload. This uses the [k8s-secrets-from-s3](https://github.com/reactiveops/rok8s-scripts#k8s-secrets-from-s3) command to generate the files.

A [SOPS method](https://github.com/reactiveops/rok8s-scripts/pull/54) is currently in PR that will use AWS KMS to decrypt secrets that can be uploaded in the deploy process.
```

**Comment by kenm47** [comment]
Added the deployment section (above) to the top of the deployments.md file. That should close #10 

The Application Configuration section here:

```

# Application Configuration

Config maps should be used for application configuration. 

Volume mounting a configmap is preferable to environment variables. 

  - Volume mounted configmaps can update in a pod when a configmap changes (where as environment variables will not).
  - Environment variable configuration in deployments are burdensome. It’s possible to use tools to help with this but without additional tools it looks like 
            - name: ENVIRONMENT_VARIABLE_NAME
              valueFrom:
                configMapKeyRef:
                  name: CONFIGMAP_NAME
                  key: CONFIGMAP_KEY


## Updating Configuration

Most apps will not re-read configuration after they have started. **Pushing out a configmap change will not trigger a restart of pods** but there is a [Github issue](https://github.com/kubernetes/kubernetes/issues/22368). 

This is a reason to tie the config changes with the deployment. The code push will trigger CI to create a new deployment with a new image tag. The config changes will be pushed and all current pods replaced with new pods that include the config change. 


## Secrets

Secrets in Kubernetes are [not encrypted](https://github.com/kubernetes/kubernetes/issues/12742) in the standard deployment. Vault may eventually be used in our standard deployment to provide secure storage of secrets. It also has the benefit that it can be used by non-Kubernetes resources and potentially allow a simplified migration procedure if a client is already using Vault.

[rok8s-scripts includes support for the CI system to create Kubernetes Secrets](https://github.com/reactiveops/rok8s-scripts#k8s-secrets-from-s3). **Plain text secrets should never be included in the source code repository**. 

There are (at least) 2 ways we have included secrets with rok8s-scripts automation:

Store the data in S3, build the Kubernetes Secrets resource on the CI server, then upload. This uses the [k8s-secrets-from-s3](https://github.com/reactiveops/rok8s-scripts#k8s-secrets-from-s3) command to generate the files.

A [SOPS method](https://github.com/reactiveops/rok8s-scripts/pull/54) is currently in PR that will use AWS KMS to decrypt secrets that can be uploaded in the deploy process.
```

At a closer looks seems more closely related to the config-maps.md file. @sairez can you see how to add this there if it's relevant? Otherwise delete it.

**Comment by ejether** [comment]
I really like these docs and I'm glad you captured them. I'm not sure they belong in Pentagon though. It seems like the goal is to provide documentation to provide to our the clients how to use the tools like kubectl and rok8s scripts? Am I reading that right @sairez 

In the case that Pentagon is an open source tool, I think it should be agnostic in terms of CI/CD and Deployment tools.

**Comment by sairez** [comment]
Indeed. We can certainly provide these docs elsewhere, though I think the examples may be useful for community members who don't have a build pipeline already established.

**Comment by philipcristiano** [comment]
Depending on how we structure modules for Pentagon it would be nice to keep an RO module "The Way" that has our client workflow docs that gets installed into their repo. Not a simple step to that point though

**Comment by ejether** [comment]
I love that idea @philipcristiano  👍 
I've been trying to come up with a good way to deliver this necessary documentation to the client and I think thats a really great method that combines the module/component idea and doesn't pollute the pentagon open source repository with extra stuff

**Comment by ejether** [comment]
Moving these docs to the internal docs repo. https://github.com/reactiveops/docs/pull/34
They can be either hosted/packaged somewhere for clients, or perhaps as a pentagon module.

**Pull request closed without merging**
