### PR TITLE
Update EnvVars

### PR DESCRIPTION
**Pull request by ejether**
replacing env-vars with yaml_source wich to 1) get scripts out of the inventory repo, 2) create a way to set env vars from arbitrary yaml files

### CODE REVIEW

**Comment by ejether** [comment]
@coreypobrien also relates to https://github.com/reactiveops/pentagon-workstation/pull/18
I'm unsure about the script name, any ideas?

**Review by coreypobrien — DISMISSED** [review]
I'm all about this. Having `env-vars.sh` in every repo is lots of WET when it comes to maintaining both the list of variables and the code to import them.

**Comment by coreypobrien** [comment]
Wait, I was confused. I think `yaml_source` should go into `pentagon-workstation` not `pentagon`

**Comment by ejether** [comment]
I debated that too, but if we make this change, then Open Source users (if we get any) will need `yaml_source` for pentagon to work. Thats why I made it a script that gets installed by Pentagon. If we need to update the script, all we need to do is `pip install -U pentagon`

but it absolutely takes it out of the repository

**Review by coreypobrien — APPROVED** [review]

**Pull request merged**
