### PR TITLE
Simplify setup location 

### PR DESCRIPTION
**Pull request by philipcristiano**
Ref #14 

Simplify the location by creating the repository in the workspace directory directly. Could be updated to default to the current directory instead of `~/workspace`

Also includes updating the error message to say which folder is needed but doesn't exist in order to be a bit more helpful.

### CODE REVIEW

**Comment by ejether** [comment]
Matching changes will need to be made in the `https://github.com/reactiveops/pentagon-workstation` project. @sairez @robwar @tizzythegrey  as Daas team members who probably deal with the most infrastructure repositories, is this change helpful, neutral or harmful?  

TL;DR;
`~/workspace/projects/<client>/<client>-infrastructure -> ~/workspace/<client>/<client>-infrastructure`


edit- gosh my tldr sucks

**Comment by sairez** [comment]
so `~/workspace/project/<project_name>/<project_name>-infrastructure` to `~/workspace/<project_name>/<project_name>-infrastructure` works fine for me.

`~/workspace/project/<project_name>/<project_name>-infrastructure` to `~/workspace/<project_name>-infrastructure` is less than ideal, because we tend to also keep application repos under the <project_name> directory alongside the infrastructure repo.

**Comment by philipcristiano** [comment]
https://github.com/reactiveops/pentagon/blob/1bcc1e1e1b49fd5d9f01d2293d9674558e1b2e4c/lib/pentagon/config/local/ansible.cfg-default.jinja#L3 for ansible using `../repo` as @sairez mentions 

I don't know that there is a reason that we need to change the workstation layout at this point. The change in Pentagon just assumes less about your layout when it starts a project. If someone wants the previous behavior `start-project` needs to be run with `--working-directory=~/workspace/projects/$client`

**Comment by ejether** [comment]
There are several references to the project directory in the `pentagon-workstation` repo that will probably throw errors and add unexpected behavior. Its not a blocker, but it will be an annoyance until its fixed. https://github.com/reactiveops/pentagon-workstation/blob/master/files/pentagon-helpers.sh#L3

Also, the pentagon workstation `hooks` directory is in the `~/workspace` directory. I see that as an aesthetic annoyance. It could probably be hidden.

**Comment by philipcristiano** [comment]
Ah right, `hooks`.

The layout for `pentagon-workstation` seems to make sense then and those values in `pentagon-workstation` would remain the same.

**Comment by philipcristiano** [comment]
Closes #26

**Comment by ejether** [comment]
Where did we land on this? @philipcristiano your last comment indicates that maybe the change isn't necessary?

I'm currently looking at how to update this to make it friendlier to the open source community doing away with the project directory (as you have done here), have `working-directory` default to ./

The rest it kind of specific to the way we use our workstation setup and we can use the `PENTAGON-workspace-directory` environment variable, set in reactiveops/pentagon-workstation to direct project creation to`~/workspace/projects/` or `~/workspace` depending on what you were thinking above.

**Comment by philipcristiano** [comment]
+1 on moving to `./`. I don't think any changes for the workstation setup are necessary. 

Trying to emulate the current setup with this change is a little more challenging if we still wanted per-client projects folders. On the DaaS side, I think they rarely create new projects, mostly clone existing ones. So even if this option changes, the procedures on the DaaS side are unlikely to change.

**Comment by ejether** [comment]
Agreed on all counts. I'll PR that change into this branch later today.

**Comment by philipcristiano** [comment]
Merged in changes from #50 by @ejether to use the current working directory.

**Pull request merged**
